### PR TITLE
Added fix for unmapped JSON payloads

### PR DESCRIPTION
**Pull request by JKetelaar**
I cannot seem to get Magento to map the JSON payload to `request->getParams()`.
Therefore I wrote this fix that reads the body of the POST request and checks if it is JSON readable, then sets the JSON values to the parameters using `setParams`.

### CODE REVIEW

**Comment by woutse** [comment]
> Any update?

Not just yet. But we'll review this as soon as possible!

**Comment by JKetelaar** [comment]
For the ones that are interested in getting it fixed, instead of waiting for the developers to work on it. You can apply the patch with the following URL: https://patch-diff.githubusercontent.com/raw/paynl/magento2-plugin/pull/57.patch

**Comment by woutse** [comment]
@JKetelaar 
Thanks again for this pullrequest. Though, could you please explain its purpose (context)? What are you trying to accomplish and why do we need this (fix)?

**Comment by JKetelaar** [comment]
I haven't really dug into this issue, but it seems to relate to servers that have Varnish as a frontend and does not properly go through the controller very well.

This change makes an abstract controller and checks if the request is received properly. If not, it will get the json from the request and then decode it. It basically is a fail-safe.

**Comment by mroeten** [comment]
Thanks for your reply, we'll review this as soon as possible!

**Pull request merged**
